
title: 「屬靈生命成長基礎」 
email: henryccyu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    「屬靈生命成長基礎」由【西雅圖證道堂】東區國語堂提供。 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spiritualformation.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: spiritualformation

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
timezone: America/Los_Angeles    

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

